# /// script
# requires-python = ">=3.9"
# ///
"""Generate elements_tab.c from rsynth's Elements.def (LGPL 2+, Nick Ing-Simmons).

Values are stored as int16 (Hz or dB, rounded to nearest integer) so the
table can be used from 16-bit code without floating point.
"""
import re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text(encoding="latin-1")
out = pathlib.Path(sys.argv[2])

# strip C comments
src_nc = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
head_re = re.compile(r'\{\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*([A-Za-z0-9_|]+)\s*,\s*\{((?:\s*\{[^}]*\}\s*,?)+)\s*\}\s*\}\s*,?', re.S)
row_re = re.compile(r'\{\s*([-0-9.]+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}')

PARAMS = ["fn","f1","f2","f3","b1","b2","b3","pn","a2","a3","a4","a5","a6","ab","av","avc","asp","af"]
elms = []
for m in head_re.finditer(src_nc):
    name, rk, du, ud, utf8, sampa, feat, body = m.groups()
    rows = row_re.findall(body)
    assert len(rows) == 18, (name, len(rows))
    elms.append((name, int(rk), int(du), int(ud), sampa, feat, rows))

def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

lines = []
lines.append("/* Generated by tools/gen_elements.py from rsynth Elements.def")
lines.append("   (Copyright (c) 1994,2001-2004 Nick Ing-Simmons, LGPL 2 or later).")
lines.append("   Do not edit; regenerate. %d elements x 18 params x 6 bytes." % len(elms))
lines.append("*/")
lines.append('#include "holmes.h"')
lines.append("")
lines.append("const klt_elm_t KLT_FAR klt_elements[%d] = {" % len(elms))
for name, rk, du, ud, sampa, feat, rows in elms:
    # feature flags: we only keep the ones the interpolator needs
    f = 0
    if "vwl" in feat.split("|"): f |= 1
    if "stp" in feat.split("|"): f |= 2
    if "nas" in feat.split("|"): f |= 4
    lines.append("  { %s, %d, %d, %d, %d, {" % (cstr(name), rk, du, ud, f))
    for p, (stdy, prop, ed, id_, rk2) in zip(PARAMS, rows):
        v = int(round(float(stdy)))
        lines.append("    {%5d,%4d,%2d,%2d,%3d}, /* %s */" % (v, int(prop), int(ed), int(id_), int(rk2), p))
    lines.append("  } },")
lines.append("};")
lines.append("const int klt_num_elements = %d;" % len(elms))
lines.append("")
# index lookup helper table for phtoelm
names = [e[0] for e in elms]
lines.append("/* element indices, in table order */")
for i, n in enumerate(names):
    lines.append("#define E_%s %d" % (n.replace("~","N_"), i))
out.write_text("\n".join(lines) + "\n")
print("elements:", len(elms))
print(" ".join("%d:%s" % (i, n) for i, n in enumerate(names)))
