# /// script
# requires-python = ">=3.9"
# ///
"""Generate klatt_tab.h: fixed-point lookup tables for klatt_fx.c.

  kfx_exptab[514]  Q15  exp(-pi * x), x = i/1024 for i = 0..513  (x in [0, 0.5])
  kfx_costab[514]  Q15  cos(2*pi * x), same x grid
  kfx_amptab[88]   int16, Klatt's dB->linear table * 1000 (parwave.c)
  kfx_b0tab[224]   int16, parwave.c B0[] (natural glottal pulse shape)
Both interpolated tables are read with a Q16 fraction: idx = u >> 6, frac = u & 63.
"""
import math, sys, pathlib

out = pathlib.Path(sys.argv[1])
N = 512
L = []
L.append("/* Generated by tools/gen_tables.py -- do not edit. */")
L.append("#ifndef KLATT_TAB_H")
L.append("#define KLATT_TAB_H")
L.append('/* On 16-bit Watcom (both the -0 and the -3 build; __386__ is only the 32-bit\n * compiler) the tables live in a far data segment so they leave DGROUP. */\n#if defined(__WATCOMC__) && !defined(__386__)\n#define %s __far\n#else\n#define %s\n#endif\n' % ("KFX_TAB_FAR", "KFX_TAB_FAR"))
L.append("#define KFX_TAB_N %d  /* entries for x in [0,0.5]; +2 guard */" % N)

def emit(name, vals, per=8):
    L.append("static const int16_t KFX_TAB_FAR %s[%d] = {" % (name, len(vals)))
    for i in range(0, len(vals), per):
        L.append("  " + ", ".join("%6d" % v for v in vals[i:i+per]) + ",")
    L.append("};")

exp_t = []
cos_t = []
for i in range(N + 2):
    x = i / (2.0 * N)
    e = int(round(math.exp(-math.pi * x) * 32768))
    if e > 32767: e = 32767
    c = int(round(math.cos(2 * math.pi * x) * 32768))
    if c > 32767: c = 32767
    if c < -32768: c = -32768
    exp_t.append(e); cos_t.append(c)
emit("kfx_exptab", exp_t)
emit("kfx_costab", cos_t)

amptable = [0.0]*13 + [6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 13.0, 14.0, 16.0, 18.0, 20.0, 22.0, 25.0, 28.0, 32.0,
   35.0, 40.0, 45.0, 51.0, 57.0, 64.0, 71.0, 80.0, 90.0, 101.0, 114.0, 128.0,
   142.0, 159.0, 179.0, 202.0, 227.0, 256.0, 284.0, 318.0, 359.0, 405.0,
   455.0, 512.0, 568.0, 638.0, 719.0, 811.0, 911.0, 1024.0, 1137.0, 1276.0,
   1438.0, 1622.0, 1823.0, 2048.0, 2273.0, 2552.0, 2875.0, 3244.0, 3645.0,
   4096.0, 4547.0, 5104.0, 5751.0, 6488.0, 7291.0, 8192.0, 9093.0, 10207.0,
   11502.0, 12976.0, 14582.0, 16384.0, 18350.0, 20644.0, 23429.0,
   26214.0, 29491.0, 32767]
assert len(amptable) == 88
emit("kfx_amptab", [int(v) for v in amptable])

B0 = [1200, 1142, 1088, 1038, 991, 948, 907, 869, 833, 799, 768, 738, 710, 683, 658,
 634,  612,  590,  570, 551, 533, 515, 499, 483, 468, 454, 440, 427, 415, 403,
 391,  380,  370,  360, 350, 341, 332, 323, 315, 307, 300, 292, 285, 278, 272,
 265,  259,  253,  247, 242, 237, 231, 226, 221, 217, 212, 208, 204, 199, 195,
 192,  188,  184,  180, 177, 174, 170, 167, 164, 161, 158, 155, 153, 150, 147,
 145,  142,  140,  137, 135, 133, 131, 128, 126, 124, 122, 120, 119, 117, 115,
 113,  111,  110,  108, 106, 105, 103, 102, 100,  99,  97,  96,  95,  93,  92, 91, 90,
  88,   87,   86,   85,  84,  83,  82,  80,  79,  78,  77,  76,  75,  75,  74, 73, 72, 71,
  70,   69,   68,   68,  67,  66,  65,  64,  64,  63,  62,  61,  61,  60,  59, 59, 58, 57,
  57,   56,   56,   55,  55,  54,  54,  53,  53,  52,  52,  51,  51,  50,  50, 49, 49, 48, 48,
  47,   47,   46,   46,  45,  45,  44,  44,  43,  43,  42,  42,  41,  41,  41, 41, 40, 40,
  39,   39,   38,   38,  38,  38,  37,  37,  36,  36,  36,  36,  35,  35,  35, 35, 34, 34, 33,
  33,   33,   33,   32,  32,  32,  32,  31,  31,  31,  31,  30,  30,  30,  30, 29, 29, 29, 29,
  28,   28,   28,   28,  27,  27]
assert len(B0) == 224, len(B0)
emit("kfx_b0tab", B0)
L.append("#endif")
out.write_text("\n".join(L) + "\n")
print("wrote", out, "bytes:", 2*(2*(N+2)+88+224))
