# /// script
# requires-python = ">=3.9"
# ///
"""Generate phtoelm_tab.c (SAMPA phone -> element index list) from rsynth's
phtoelm.def and the element order in elements_tab.c.  LGPL 2+ (Nick Ing-Simmons).
"""
import re, sys, pathlib
defs = pathlib.Path(sys.argv[1]).read_text()
elm = pathlib.Path(sys.argv[2]).read_text()
out = pathlib.Path(sys.argv[3])
names = {}
for m in re.finditer(r'#define E_(\w+) (\d+)', elm):
    names[m.group(1)] = int(m.group(2))
entries = []
for m in re.finditer(r'enter\(((?:"(?:[^"\\]|\\.)*"\s*,\s*)+)NULL\)', defs):
    strs = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    ph = strs[0].encode().decode("unicode_escape")
    els = strs[1:]
    idx = [names[e] for e in els]
    entries.append((ph, idx))
# longest phone string first so a linear scan gives longest match
entries.sort(key=lambda e: (-len(e[0]), e[0]))
maxn = max(len(e[1]) for e in entries)
L = ["/* Generated by tools/gen_phtoelm.py from rsynth phtoelm.def",
     "   (Copyright (c) 1994,2001-2004 Nick Ing-Simmons, LGPL 2 or later). */",
     '#include "holmes.h"', "",
     "const klt_ph_t klt_phtab[%d] = {" % len(entries)]
for ph, idx in entries:
    cs = ph.replace("\\", "\\\\").replace('"', '\\"')
    L.append('  { "%s", %d, { %s } },' % (cs, len(idx), ", ".join(str(i) for i in idx + [0] * (maxn - len(idx)))))
L.append("};")
L.append("const int klt_num_phtab = %d;" % len(entries))
out.write_text("\n".join(L) + "\n")
print("phones:", len(entries), "max elements per phone:", maxn)
