#!/usr/bin/env python3
"""Generate espk/ucdtab.h: Unicode general categories and simple case maps for
U+0000..U+052F (Latin, Latin Extended, IPA, Greek, Cyrillic) from Python's
unicodedata.  Everything above is treated as 'other letter' (English only)."""
import unicodedata, sys
N = 0x530
cats = ["Cc","Cf","Cn","Co","Cs","Ii","Ll","Lm","Lo","Lt","Lu","Mc","Me","Mn","Nd","Nl","No","Pc","Pd","Pe","Pf","Pi","Po","Ps","Sc","Sk","Sm","So","Zl","Zp","Zs"]
out = ["/* generated by tools/gen_ucd.py (Unicode %s) */" % unicodedata.unidata_version, "#define UCDTAB_N 0x%X" % N]
out.append("static const unsigned char ucd_cat_tab[UCDTAB_N] = {")
row = []
for c in range(N):
    cat = unicodedata.category(chr(c))
    row.append("%d" % cats.index(cat))
    if len(row) == 32: out.append(" " + ",".join(row) + ","); row = []
out.append("};")
for name, fn in (("ucd_upper_tab", str.upper), ("ucd_lower_tab", str.lower)):
    out.append("static const unsigned short %s[UCDTAB_N] = {" % name)
    row = []
    for c in range(N):
        m = fn(chr(c))
        v = ord(m) if len(m) == 1 and ord(m) < 0x10000 else c
        row.append("%d" % v)
        if len(row) == 16: out.append(" " + ",".join(row) + ","); row = []
    out.append("};")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
