#!/usr/bin/env python3
"""Extract SPEECH.COM's 1-bit phonemes from horndrv's PHONEME.C and render a phoneme string to WAV.
Bit clock: PlayPhoneme waits for the 8254 refresh toggle (port 61h bit 4) low then high per bit = 30.17 us,
so 33,145 bit/s. Output: 22050 Hz 8-bit unsigned, each sample = mean of the ~1.5 bits it covers.
usage: uv run mkretro.py "H EH L OH   W ER L D" out.wav      (phoneme names as in aPhoneme[], space = pause)
       uv run mkretro.py --dump tables.c                        (emit C tables for the DOS engine)"""
import re, sys, struct
src = open('../horndrv/src/PHONEME.C', 'rb').read().decode('latin-1').replace('\r', '')
arrays = {}
for m in re.finditer(r'static char (achPhoneme\w+)\[\] =\s*\{(.*?)\};', src, re.S):
    arrays[m.group(1)] = bytes(int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(2)))
tab = re.search(r'PHONEME aPhoneme\[\] =\s*\{(.*?)\};', src, re.S).group(1)
phon = []; refs = []      # refs: (name, array name, bytes played) -- "E", "C", "O" play the first half of EE, CH, OH
for m in re.finditer(r'\{\s*"([^"]+)"\s*,\s*(achPhoneme\w+)\s*,\s*ARRAYSIZE_M\(\w+\)(/2)?\s*\}', tab):
    name, arr, half = m.group(1), m.group(2), m.group(3)
    data = arrays[arr]; n = len(data) // 2 if half else len(data)
    phon.append((name, data[:n])); refs.append((name, arr, n))
used = sorted(set(a for _, a, _ in refs), key=lambda a: [r[1] for r in refs].index(a))   # first use order
BITRATE = 1e6 / 30.17
def render(seq, rate=22050):
    bits = []
    for tok in seq:
        for name, data in phon:
            if name == tok:
                for _ in range(len(name)):            # horndrv repeats a phoneme strlen(name) times
                    for b in data:
                        for k in range(7, -1, -1): bits.append((b >> k) & 1)
                break
        else:
            if tok == ' ' or tok == '': pass
            else: print('unknown phoneme', tok, file=sys.stderr)
    out = bytearray(); pos = 0.0; step = BITRATE / rate
    while pos + step <= len(bits):
        i0, i1 = int(pos), int(pos + step)
        seg = bits[i0:i1 + 1] or [0]
        out.append(int(128 + (sum(seg) / len(seg) - 0.5) * 200)); pos += step
    return bytes(out)
def wav(path, pcm, rate=22050):
    with open(path, 'wb') as f:
        f.write(b'RIFF' + struct.pack('<I', 36 + len(pcm)) + b'WAVEfmt ' + struct.pack('<IHHIIHH', 16, 1, 1, rate, rate, 1, 8) + b'data' + struct.pack('<I', len(pcm)) + pcm)
if __name__ == '__main__':
    if sys.argv[1] == '--dump':
        with open(sys.argv[2], 'w') as f:
            f.write('/* generated by mkretro.py from horndrv PHONEME.C (SPEECH.COM 1983 1-bit phonemes) */\n')
            f.write('#ifdef __WATCOMC__\n#define RETRO_FAR __far\n#else\n#define RETRO_FAR\n#endif\n')
            f.write('typedef struct { const char *name; const unsigned char RETRO_FAR *bits; unsigned len; } retro_ph_t;\n')
            for i, arr in enumerate(used):        # each record once; the half-length entries point at the full one
                f.write('static const unsigned char RETRO_FAR rp%d[%d] = {%s};\n' % (i, len(arrays[arr]), ','.join(str(b) for b in arrays[arr])))
            f.write('const retro_ph_t retro_ph[] = {\n' + ''.join('  {"%s", rp%d, %d},\n' % (n, used.index(a), l) for n, a, l in refs) + '};\nconst int retro_nph = %d;\n' % len(refs))
        print(len(refs), 'phonemes,', sum(len(arrays[a]) for a in used), 'bytes in', len(used), 'records')
    else:
        pcm = render(sys.argv[1].split(' ')); wav(sys.argv[2], pcm); print(len(pcm) / 22050, 's;', len(phon), 'phonemes:', ' '.join(n for n, _ in phon))
